// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *gpg_key_text;
extern Fl_Text_Editor *message_text;
#include <FL/Fl_Button.H>
extern Fl_Button *encrypt_button;
extern "C" { Fl_Double_Window* make_window(); }
#endif
