// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "gui.h"

static Fl_Text_Editor *gpg_key_text=(Fl_Text_Editor *)0;

static Fl_Text_Editor *message_text=(Fl_Text_Editor *)0;

Fl_Button *encrypt_button=(Fl_Button *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(440, 490);
    w = o; if (w) {/* empty */}
    { gpg_key_text = new Fl_Text_Editor(5, 25, 430, 195, "GPG key:");
    } // Fl_Text_Editor* gpg_key_text
    { message_text = new Fl_Text_Editor(5, 245, 430, 195, "Message:");
    } // Fl_Text_Editor* message_text
    { encrypt_button = new Fl_Button(160, 450, 120, 30, "Encrypt");
    } // Fl_Button* encrypt_button
    o->end();
  } // Fl_Double_Window* o
  return w;
}
